project:
  type: website
  output-dir: docs

website:
  title: "Oguz'un Analitik Labı"
  navbar:
    search: true
    left:
      - text: Ana Sayfa
        href: index.qmd
      - text: Hakkımda
        href: about.qmd
      - text: Gönderiler
        href: posts.qmd
      - text: "MUY665 Ders Çıktıları"
        menu:
          - text: Portfolyo
            href: portfolyo.qmd
          - text: Proje
            href: proje.qmd
            
    tools:
      - icon: github
        href: https://github.com/oguzsenel
      - icon: twitter
        href: https://x.com/oguzsenel_
      - icon: linkedin
        href: https://www.linkedin.com/in/oguzhansenel/

  sidebar:
    - title: "Çalışmalar"
      style: "docked"
      search: true
      contents:
        - portfolyo.qmd
        - portfolyo/calisma1.qmd
        - portfolyo/calisma2.qmd  

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - MUY665 - Bahar 2026" 
    border: true

format:
  html:
    toc: true
    toc-location: left
    theme: simplex
    css: styles.css

editor: visual